version: "3"

services:

  tapula-api:
    build:
      context: ./cmd/api
    image: tapula-api
    ports:
      - 3333

  tapula:
    build:
      context: .
    image: tapula
    depends_on:
      - tapula-api